### ISSUE TITLE
Breaking changes with v1

### ISSUE THREAD

**Issue by peterbud** [smastrom/notivue#5]
Updating to v 1.0.2 results the following error:
`[Vue warn]: Extraneous non-props attributes (position, pause-on-hover) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. `

With version 0.9.4 it works, and no error is visible.

Was there any change between the two versions? Position and pause-on-hover is now not the props of the component?

I'm using nuxt 3.6.1

**Comment by smastrom** [comment]
Hi Peter. Yes, I released a new major version, therefore there are some breaking changes in the API.

I was planning on writing a migration guide, but I think the best thing to do is to read the [new documentation](https://notivuedocs.netlify.app/) and then adapt your code.

Regarding your issue, configuration props have been moved to plugin options, which in your case are now located in _plugins/notivue.client.ts_:

```ts
import { notivue } from 'notivue'

export default defineNuxtPlugin(({ vueApp }) => {
  vueApp.use(notivue, {
    pauseOnHover: true
    // ... Other options
  })
})
```

If you need to update the above options dynamically, use the `useNotivue` composable:

```vue
<script setup>
import { useNotivue } from 'notivue'

const config = useNotivue()

function updateConfig() {
  config.position.value = 'top-left'
  config.pauseOnTouch.value = true
}
</script>
```

In addition to that, there are new configuration options such as `pauseOnTabChange` and `limit`.  The `options` prop, has been renamed to `notifications` and can be found in the configuration object as well.

But the most important change is that starting from v1.0.0 `<Notivue />` exposes the notification item via `v-slot` making a hundred times easier using custom components:

```vue
<script setup>
import { Notivue, Notifications } from 'notivue'
</script>

<template>
  <Notivue v-slot="item">
    <Notifications :item="item" /> 
    <!-- Or use your component in place of Notifications -->
  </Notivue>
</template>
```

Please take a look at the [new documentation](https://notivuedocs.netlify.app/), which contains all the information you need.

Of course, let me know if you need any further assistance.

**Comment by peterbud** [comment]
Hi @smastrom , many thanks for the help - I have successfully managed to update my custom notification component, and it works.

The only problem still is the exported types are not available:
<img width="526" alt="image" src="https://github.com/smastrom/notivue/assets/7863452/dca056d3-9b2c-497e-81f3-70eca0c82bab">

Is there any chance to fix them?

Another question, which I cannot find in the new documentation was how to make a composable which renders a custom component?

There was something like this in the previous doc:
```typescript
const methods = ['success', 'error', 'warning', 'info'] as const

  methods.forEach((method) => {
    customPush[method] = ({ props = {}, ...options }) =>
      push[method]({
        ...options,
        render: {
          component: () => Toast,
          props: ({ notivueProps }) => ({
            ...notivueProps,
            ...props,
          }),
        },
      })
  })
```

I'm not sure what is the designated way to pass all the props to the custom component? Maybe if you have an example included in the doc, that would be a great help I believe.

**Comment by smastrom** [comment]
Hi @peterbud, types are exported. The import name is `NotivueSlot` and not `NotivueItem`, my bad for not updating the documentation, which I did now.

Regarding the other question, as I told you in the previous answer, v1 brings breaking changes on how custom components are handled.

I'll try to write an example here, but you can find it on the docs [section](https://notivuedocs.netlify.app/custom-components/usage.html) as well.

Starting from v1, the `render` property of the `UserPushOptions` interface (which is the object you pass as only parameter to push) doesn't exist anymore. Instead, custom components are passed as default slot inside `<Notivue />`. This keeps your custom components in a single place and is a way better DX as being more declarative.

**app.vue**

```vue
<script setup lang="ts">
import { Notivue } from 'notivue';

import Custom from './components/Custom.vue';
</script>

<template>
  <Notivue v-slot="item">
    <Custom :item="item" />
  </Notivue>
</template>
```

Out of curiosity, you can try to see the data that are exposed by serializing the notification item (`NotivueSlot` interface):

```vue
<template>
  <Notivue v-slot="item">
    <div> {{ JSON.stringify(item) }} </div>
  </Notivue>
</template>
```

This object contains the data needed to render the notification content.

Always starting from v1, `UserPushOptions` interface has now a `props` property which can be used to pass any kind of data you want to include in the notification object (`NotivueSlot`).

So let's say you call push with:

```ts
push.success({
   message: 'This is a success message',
   props: {
      customName: 'Giovanni',
      isCriticalToast: true,
   },
})
```

You can now get the value of `item.props.customName` inside your custom component along with `item.message`, `item.type` etc.

According to that, you can use the same props to render different components, for example:

```vue
<script setup>
import { Notivue, Notifications } from 'notivue'

import MyToast from './MyToast.vue'
import MyOtherToast from './MyOtherToast.vue'
</script>

<template>
  <Notivue v-slot="item">
    <MyToast
      v-if="item.props.isCriticalToast" 
      :item="item"
    />
    <MyOtherToast
      v-else-if="item.props.isOtherToast" 
      :item="item"
    />
    <!-- Use default notifications -->
    <Notifications
      v-else 
      :item="item"
    />
  </Notivue>
</template>
```

So regarding your specific case, you don't need anymore to create a custom composable for a custom component. You simply call any push method and that's it.

For example, if you're only using one single custom component, that's how you would do it:

`push.success('This is a success message')`

```vue
<script setup>
import { Notivue } from 'notivue'

import Toast from './Toast.vue'
</script>

<template>
  <Notivue v-slot="item">
    <Toast
      :item="item"
    />
  </Notivue>
</template>
```

Let me know if everything's clear and if you need further assistance.

Simone

**Comment by peterbud** [comment]
Thanks @smastrom - based on your explanation I have managed to fix it and it works now.

However the type exports are not working properly.

Here is a small minimal repro at stackblitz to see the issue for yourself:
https://stackblitz.com/edit/github-zqfp5c-xrihfa?file=push.ts

Open the project in your browser, let it start up, and you will see the squiggle line:

<img width="423" alt="image" src="https://github.com/smastrom/notivue/assets/7863452/af6febb9-f51d-4dc1-945d-cd250e2a3f7d">

**Comment by smastrom** [comment]
There you go @peterbud. Unfortunately, this bug was happening only in some scenarios like StackBlitz. Now types will work 100%.

Please update using:

`pnpm add notivue@latest`

![Screenshot 2023-07-12 alle 01 54 50](https://github.com/smastrom/notivue/assets/60471784/643ba88c-d973-4310-99d6-cde227bb224c)

**Comment by peterbud** [comment]
Many thanks - perfect!!
